const nflTeams = [
    {
      city: "Arizona",
      name: "Cardinals",
      cPrim: "#97233F",
      cSecn: "#FFB612",
      wins: 0,
      losses: 0,
      ties: 0,
      imgurl: "https://static.www.nfl.com/image/private/f_auto/league/u9fltoslqdsyao8cpm0k",
    },
    {
      city: "Atlanta",
      name: "Falcons",
      cPrim: "#A71930",
      cSecn: "#000000",
      wins: 0,
      losses: 0,
      ties: 0,
      imgurl: "https://static.www.nfl.com/image/private/f_auto/league/d8m7hzpsbrl6pnqht8op",
    },
    {
      city: "Carolina",
      name: "Panthers",
      cPrim: "#0085CA",
      cSecn: "#101820",
      wins: 0,
      losses: 0,
      ties: 0,
      imgurl: "https://static.www.nfl.com/image/private/f_auto/league/ervfzgrqdpnc7lh5gqwq",
    },
    {
      city: "Chicago",
      name: "Bears",
      cPrim: "#0B162A",
      cSecn: "#C83803",
      wins: 0,
      losses: 0,
      ties: 0,
      imgurl: "https://static.www.nfl.com/image/private/f_auto/league/ra0poq2ivwyahbaq86d2",
    },
    {
      city: "Dallas",
      name: "Cowboys",
      cPrim: "#041E42",
      cSecn: "#869397",
      wins: 0,
      losses: 0,
      ties: 0,
      imgurl: "https://static.www.nfl.com/image/private/f_auto/league/ieid8hoygzdlmzo0tnf6",
    },
    {
      city: "Detroit",
      name: "Lions",
      cPrim: "#0076B6",
      cSecn: "#B0B7BC",
      wins: 0,
      losses: 0,
      ties: 0,
      imgurl: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/ocvxwnapdvwevupe4tpr",
    },
    {
      city: "Green Bay",
      name: "Packers",
      cPrim: "#203731",
      cSecn: "#FFB612",
      wins: 0,
      losses: 0,
      ties: 0,
      imgurl: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/gppfvr7n8gljgjaqux2x",
    },
    {
      city: "Los Angeles",
      name: "Rams",
      cPrim: "#003594",
      cSecn: "#FFA300",
      wins: 0,
      losses: 0,
      ties: 0,
      imgurl: "https://static.www.nfl.com/image/private/f_auto/league/ayvwcmluj2ohkdlbiegi",
    },
    {
      city: "New Orleans",
      name: "Saints",
      cPrim: "#D3BC8D",
      cSecn: "#101820",
      wins: 0,
      losses: 0,
      ties: 0,
      imgurl: "https://static.www.nfl.com/image/private/f_auto/league/grhjkahghjkk17v43hdx",
    },
    {
      city: "New York",
      name: "Giants",
      cPrim: "#0B2265",
      cSecn: "#A71930",
      wins: 0,
      losses: 0,
      ties: 0,
      imgurl: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/t6mhdmgizi6qhndh8b9p",
    },
    {
      city: "Philadelphia",
      name: "Eagles",
      cPrim: "#004C54",
      cSecn: "#A5ACAF",
      wins: 0,
      losses: 0,
      ties: 0,
      imgurl: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/puhrqgj71gobgdkdo6uq",
    },
    {
      city: "San Francisco",
      name: "49ers",
      cPrim: "#AA0000",
      cSecn: "#B3995D",
      wins: 0,
      losses: 0,
      ties: 0,
      imgurl: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/dxibuyxbk0b9ua5ih9hn",
    },
    {
      city: "Seattle",
      name: "Seahawks",
      cPrim: "#002244",
      cSecn: "#69BE28",
      wins: 0,
      losses: 0,
      ties: 0,
      imgurl: "https://res.cloudinary.com/nflleague/image/private/f_auto/league/gcytzwpjdzbpwnwxincg",
    },
    {
      city: "Tampa Bay",
      name: "Buccaneers",
      cPrim: "#D50A0A",
      cSecn: "#B1BABF",
      wins: 0,
      losses: 0,
      ties: 0,
      imgurl: "https://static.www.nfl.com/image/private/f_auto/league/v8uqiualryypwqgvwcih",
    },
    {
      city: "Washington",
      name: "Commanders",
      cPrim: "#773141",
      cSecn: "#FFB612",
      wins: 0,
      losses: 0,
      ties: 0,
      imgurl: "https://static.www.nfl.com/image/private/f_auto/league/xymxwrxtyj9fhaemhdyd",
    },
  ];